### ISSUE TITLE
Improve Nethermind service with support to more Nethermind module options

### ISSUE THREAD

**Issue by aldoborrero** [nix-community/ethereum.nix#108]
Currently, the Nethermind service is very simplistic in its form. We can add support to more Nethermind module options.

**Comment by ameya-deshmukh** [comment]
Hey @aldoborrero are you still working on this? If not, would love to pick it up!

**Comment by aldoborrero** [comment]
Hi @ameya-deshmukh if you want to tackle it, go ahead! I'll assign this task to you! Thanks!

**Comment by aldoborrero** [comment]
@ameya-deshmukh I'll remove the assignation of the task to you as it has been any activity since then.

**Comment by ameya-deshmukh** [comment]
Sure.
