### ISSUE TITLE
Add support for Obol Networks: Charon

### ISSUE THREAD

**Issue by aldoborrero** [nix-community/ethereum.nix#119]
[Charon](https://github.com/ObolNetwork/charon) is a Proof of Stake Ethereum Distributed Validator Client. We should add support to the tool.

**Comment by selfuryon** [comment]
I can take that, we are going to test charon in these two weeks at work.

**Comment by aldoborrero** [comment]
Ossom! I've been researching Charon these past few days and wanted to try it too!
