### ISSUE TITLE
Add nix-update to workflows

### ISSUE THREAD

**Issue by selfuryon** [nix-community/ethereum.nix#121]
Manual updating is a little bit frustrating, `nix-update` is a huge step forward, but I suggest making a workflow similar to `Updates nix flakes` for updating packages (which I can update without setting specific version like in `web3signer`). 
Do PR in next several days

**Comment by aldoborrero** [comment]
Speaking with @Mic92 about a possible way of achieving this with a Github Action would be:

1. We can take inspiration from  (nix-updater-action)[https://github.com/knl/niv-updater-action).
2. We can replace `niv` with `nix-update`.
3. We can list the packages in JSON with the command `nix flake show --json`
4. Iterate and update those we are interested in updating.
5. Done

**Comment by brianmcgee** [comment]
@selfuryon have you had any time to look into this?
