### ISSUE TITLE
Package Besu from sources (if it makes sense)

### ISSUE THREAD

**Issue by aldoborrero** [nix-community/ethereum.nix#124]
We're currently using a packaged version of Besu, but ideally, we should compile it from sources instead. 

Let's evaluate the difficulty of packaging Besu with Nix and determine if it's worthwhile not to do it (mostly, it will depend on how `gradle` is configured on their end and what tricks we may perform).

**Comment by selfuryon** [comment]
I'll try to figure out how to do that (I haven't experienced with Java, but saw some packaged apps in nixpkgs)

**Comment by aldoborrero** [comment]
@selfuryon I can help you with that if necessary.

**Comment by selfuryon** [comment]
@aldoborrero Yeah, seems like I need some help with gradle plugins, how can I contact with you about that?

**Comment by aldoborrero** [comment]
@selfuryon I'm available on Telegram or Matrix, whatever suits you better. I'll also include @brianmcgee as he recently packaged a Java app so his insights might be useful.

**Comment by brianmcgee** [comment]
Relevant: https://bmcgee.ie/posts/2023/02/nix-what-are-fixed-output-derivations-and-why-use-them/

**Comment by aldoborrero** [comment]
@brianmcgee you have been battling lately with JVM and Nix, just evaluate if it's worthwhile or not. If it's not then close the issue, please.

**Comment by brianmcgee** [comment]
I'll have a look at some point this week

**Comment by aldoborrero** [comment]
I'll mark this issue as closed for now. We can always get back to the idea if it makes sense.
