### ISSUE TITLE
statix/nix-update reference

### ISSUE THREAD

**Issue by selfuryon** [nix-community/ethereum.nix#133]
Hello!
While preparing #121 I realize that we [use](https://github.com/nix-community/ethereum.nix/blob/main/nix/shell.nix#L12) `nix-update` and `statix` from stable nixpkgs input in devShell instead of their specific inputs. I found it because `nix-update` from stable channel doesn't support `--flake` argument.

I see two ways to resolve that:
* we use these packages from related inputs with `follows='nixpkgs-unstable'`, but we need to rebuild them cuz no caches 
* we use these packages from `nixpkgs-unstable` (and remove `nix-update` and `statix` inputs) because it tracks the last app versions very well, and we don't need to rebuild them locally

I'd prefer the second way. What do you think about that?

**Comment by aldoborrero** [comment]
The second approach is the way!
