### ISSUE TITLE
Add a service for mev-boost

### ISSUE THREAD

**Issue by aldoborrero** [nix-community/ethereum.nix#21]
Currently, running a [mev-boost](https://github.com/flashbots/mev-boost) instance [requires some configuration](https://github.com/eth-educators/ethstaker-guides/blob/main/prepare-for-the-merge.md#installing-mev-boost) we can take care of by implementing a service.

**Comment by ameya-deshmukh** [comment]
Hi, is this still available? Would love to take it up. :)

**Comment by aldoborrero** [comment]
@ameya-deshmukh Please go ahead!

**Comment by aldoborrero** [comment]
We had since then one PR bringing support to `mev-boost` by @RichardWarfield . I adapted his work on [this PR ](https://github.com/nix-community/ethereum.nix/pull/280).

**Comment by aldoborrero** [comment]
Closed by #280
