### ISSUE TITLE
Readme instructions for non-flake usage seem out of date

### ISSUE THREAD

**Issue by RichardWarfield** [nix-community/ethereum.nix#211]
This didn't work (error was `/nix/store/kzmc1r6xq2cpjj7p3wgsb4cgppykgzxh-source/overlays.nix': No such file or directory`):
```
    (import "${fetchTarball "https://github.com/nix-community/ethereum.nix/archive/main.tar.gz"}/overlays.nix")
```

The following works:

```
    (import "${fetchTarball "https://github.com/nix-community/ethereum.nix/archive/main.tar.gz"}").overlays.default
```

**Comment by aldoborrero** [comment]
Hi, @RichardWarfield thanks for pointing it out! The README needs more love (and the majority of it has to be migrated to the `mkdocs`).

I'll revamp the README this week and improve the instructions!

**Comment by aldoborrero** [comment]
This issue is not longer relevant related to the README. I'm focused on improving the documentation so I'll make sure it covers this explicitly there.
