### ISSUE TITLE
updateFlakePackages action is failing

### ISSUE THREAD

**Issue by brianmcgee** [nix-community/ethereum.nix#218]
See the latest run here: https://github.com/nix-community/ethereum.nix/actions/runs/4730426413/jobs/8394121838

**Comment by selfuryon** [comment]
Yeah, the problem is in lighthouse update, repeat that locally.

**Comment by selfuryon** [comment]
Tested it, `nix-update` doesn't work with `CargoLock`, so I will raise an issue in `nix-update` and suggest excluding `lighthouse` from periodic package updates.

**Comment by selfuryon** [comment]
The last v0.17.0 version of `nix-update` is working, so need to wait it for [merging in `nixpkgs-unstable`](https://nixpk.gs/pr-tracker.html?pr=227022). 

But now `lighthouse` version is 4.0.2-rc.0, so `nix-update` will revert it to 4.0.1, so we need to disable `lighthouse` update anyway until they release a new stable version.

**Comment by brianmcgee** [comment]
We could point directly to the flake for nix-update instead of relying on nixpkgs version.

**Comment by selfuryon** [comment]
>We could point directly to the flake for nix-update instead of relying on nixpkgs version.

Yeah, but `nix-update` is installed from `nix-update-action` github actions, which got that from `nixpkgs` input. Maybe it's a good idea to refactor [`nix-update-action`](https://github.com/selfuryon/nix-update-action) to specify from where we should get our tools.

But anyway `nix-update` is already in a target branch :)
