### ISSUE TITLE
Latest Prysm version is crashlooping when running

### ISSUE THREAD

**Issue by aldoborrero** [nix-community/ethereum.nix#246]
Although we're compiling fine `Prysm`, it seems when running it's crash looping with the following stack trace:

<details>
<summary>Prysm stack trace</summary>
<pre><code>
Apr 23 19:36:33 localhost beacon-chain[25585]: time="2023-04-23 19:36:33" level=error msg="Panic occurred" error="reflect: call of reflect.Value.Int on struct Value" prefix=sync topic="/eth2/beacon_chain/req/status/1/ssz_snappy"
Apr 23 19:36:33 localhost beacon-chain[25585]: time="2023-04-23 19:36:33" level=error msg="goroutine 4239125 [running]:
Apr 23 19:36:33 localhost beacon-chain[25585]: runtime/debug.Stack()
Apr 23 19:36:33 localhost beacon-chain[25585]:         runtime/debug/stack.go:24 +0x65
Apr 23 19:36:33 localhost beacon-chain[25585]: github.com/prysmaticlabs/prysm/v4/beacon-chain/sync.(*Service).registerRPC.func1.1()
Apr 23 19:36:33 localhost beacon-chain[25585]:         github.com/prysmaticlabs/prysm/v4/beacon-chain/sync/rpc.go:116 +0x13f
Apr 23 19:36:33 localhost beacon-chain[25585]: panic({0x1c25dc0, 0xc0567904f8})
Apr 23 19:36:33 localhost beacon-chain[25585]:         runtime/panic.go:890 +0x263
Apr 23 19:36:33 localhost beacon-chain[25585]: reflect.Value.Int(...)
Apr 23 19:36:33 localhost beacon-chain[25585]:         reflect/value.go:1461
Apr 23 19:36:33 localhost beacon-chain[25585]: github.com/trailofbits/go-mutexasserts.RWMutexRLocked(0x42ea43?)
Apr 23 19:36:33 localhost beacon-chain[25585]:         github.com/trailofbits/go-mutexasserts@v0.0.0-20200708152505-19999e7d3cef/mutex.go:22 +0x13d
Apr 23 19:36:33 localhost beacon-chain[25585]: github.com/prysmaticlabs/prysm/v4/beacon-chain/sync.(*limiter).retrieveCollector(0xc012783fb0, {0x2012a9a, 0x11})
Apr 23 19:36:33 localhost beacon-chain[25585]:         github.com/prysmaticlabs/prysm/v4/beacon-chain/sync/rate_limiter.go:190 +0x48
Apr 23 19:36:33 localhost beacon-chain[25585]: github.com/prysmaticlabs/prysm/v4/beacon-chain/sync.(*limiter).validateRawRpcRequest(0xc012783fb0, {0x24e17c0, 0xc049568800})
Apr 23 19:36:33 localhost beacon-chain[25585]:         github.com/prysmaticlabs/prysm/v4/beacon-chain/sync/rate_limiter.go:115 +0xcd
Apr 23 19:36:33 localhost beacon-chain[25585]: github.com/prysmaticlabs/prysm/v4/beacon-chain/sync.(*Service).registerRPC.func1({0x24e17c0?, 0xc049568800})
Apr 23 19:36:33 localhost beacon-chain[25585]:         github.com/prysmaticlabs/prysm/v4/beacon-chain/sync/rpc.go:146 +0x799
Apr 23 19:36:33 localhost beacon-chain[25585]: github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1({0xc029f68330, 0x2a}, {0x7f46d84f3c80?, 0xc049568800})
Apr 23 19:36:33 localhost beacon-chain[25585]:         github.com/libp2p/go-libp2p@v0.26.2/p2p/host/basic/basic_host.go:593 +0x76
Apr 23 19:36:33 localhost beacon-chain[25585]: created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
Apr 23 19:36:33 localhost beacon-chain[25585]:         github.com/libp2p/go-libp2p@v0.26.2/p2p/host/basic/basic_host.go:434 +0x74f
Apr 23 19:36:33 localhost beacon-chain[25585]: " prefix=sync topic="/eth2/beacon_chain/req/status/1/ssz_snappy"
</code></pre>
</details>

Previously we have run and executed Prysm without issues (and also we have a separate discussion about the benefits, if any, of switching to compile the program with Bazel in #171).

**Comment by brianmcgee** [comment]
I've been unable to replicate the issue with latest main. Prysm beacon is syncing without issue for Goerli on one of my Intel NUCs running NixOS. @zimbatm

**Comment by aldoborrero** [comment]
I was conducting same testing on my local machine the past week (before leaving for the holidays) and I obtained the same results (no crash-loopings so far).

I think more information is necessary to narrow it down (potentially if @zimbatm was using certain specific flags that trigger that behavior).

**Comment by aldoborrero** [comment]
I'll close this issue for now until it appears again.
