### ISSUE TITLE
Add support to donations

### ISSUE THREAD

**Issue by dzmitry-lahoda** [nix-community/ethereum.nix#262]
please add if possible

**Comment by aldoborrero** [comment]
I'm considering multiple options, we have the following ones:

- [ ] [Github Sponsors](https://github.com/sponsors).
- [ ] [Gitcoin Grants](https://bounties.gitcoin.co/grants).
- [ ] [Ethereum Foundation Grants](https://ethereum.org/en/community/grants/)

In terms of donations we can use the following options:

- [ ] Using a multi-sig Gnosis Safe Wallet (as you described).
- [ ] Using the Crypto Donation button from "Open Collective" (as you described).

Let me know if we're missing more alternatives to consider first. It will certainly have legal implications, so we need to research each option accordingly.

**Comment by aldoborrero** [comment]
I think this should be moved to a "discussion" as it fits more there.
