### ISSUE TITLE
Feature: support solc and ilk

### ISSUE THREAD

**Issue by sambacha** [nix-community/ethereum.nix#30]
Solidity support can be taken from dapptools, and for foundry there is an existing nix integration maybe he can contribute it here idk

**Comment by aldoborrero** [comment]
After thinking about this more carefully, two things:

- Foundry support has been already added on #126 
- Solidity is pretty up-to-date on `nixpkgs` upstream already (not sure if it's worthwhile to bring it here)

So I'll close this issue unless there are any specific objections.

**Comment by dzmitry-lahoda** [comment]
in theory this project could provide canonical shell(with solc/foundry) and builder(offline foundry with solc selector) instead.
