### ISSUE TITLE
Add support for reth

### ISSUE THREAD

**Issue by selfuryon** [nix-community/ethereum.nix#323]
Today was the first `reth` alpha release, we need to add that. The main problem is they use rust `1.70.0` which isn't released yet in nixpkgs, so I'm awaiting the needed rust release will be available in nixpkgs.

**Comment by aldoborrero** [comment]
@selfuryon I believe there are ways of using the latest and greatest with [Oxalica](https://github.com/oxalica/rust-overlay), we can use it as needed til support comes to nixpkgs.

**Comment by selfuryon** [comment]
Yeah, good idea, I'll try to do that!
