### ISSUE TITLE
Flatten the `packages/` directory (following the new nixpkgs convention)?

### ISSUE THREAD

**Issue by mitchmindtree** [nix-community/ethereum.nix#461]
### Context

Currently, packages are divided into arbitrary categories. Already there are a few packages that could likely fit under more than one category, e.g. `utils`.

Recently, the `nixpkgs` crew kicked off the process of flattening the `nixpkgs/pkgs` directory into [a single `by-name` directory](https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name) to:

1. make it easier to contribute packages (without having to pick from many potentially compatible categories and bikeshedding about which is correct with maintainers) and
2. remove the need for the `top-level/all-packages.nix` declarations which have become an unordered mess, instead automatically collecting packages by taking advantage of the `by-name` standard layout.

I assume the `by-name` sub directory is mostly to keep this new relocation from the individual categories directory clean, and as far as I understand the two-letter prefix subdirectories are to assist programs that would otherwise struggle to handle nixpkgs' tens of thousands of packages under a single directory. Neither of which I imagine would be necessary for the `ethereum.nix` repo.

### Description

Change the `packages` directory to directly contain a single directory for each package, removing the unnecessary categories. E.g.

```
packages/besu/
packages/bls/
packages/blst/
packages/charon/
...
```

I'm happy to open a PR for this if there's interest!

---

### packages/default.nix

After this (as follow-up PR/work) we could change `packages/default.nix` to automatically collect packages using `builtins.readDir`. This will require reconsidering how we approach exposing the "unstable" nixpkgs set (e.g. providing a list of package names that are to be called with `callPackageUnstable`, or alternatively only use the unstable package set). Packages that are also dependencies of other packages can be provided via the overlay (rather than being manually passed in the `callPackage` args as is currently the case with `foundry`, `bls`, `blst`, etc).

---

### W.r.t. categories

If categories are deemed necessary for some downstream use, perhaps they are better expressed by extending the package's `meta` attrs so that they can be programmatically discovered without influencing the directory structure?

### Before submitting

- [X] I have verified that my idea is a change request and not a bug report

**Comment by aldoborrero** [comment]
Yep, I was going to write exactly this as I have done on my `mynixpkgs` repository. Also, I would rename `packages` to `pkgs` to follow even more `nixpkgs` conventions.

So, I'm 100% up for this change.
