### ISSUE TITLE
Add support for plugeth plugins

### ISSUE THREAD

**Issue by aldoborrero** [nix-community/ethereum.nix#5]
Just as in `nixpkgs` we can find `terraform` supporting plugins, we should do the same with [`plugeth`](https://github.com/openrelayxyz/plugeth-plugins).

**Comment by aldoborrero** [comment]
Although `Plugeth` is a very good fork of `Geth` but is a low-priority effort as it's not being used that widely. 

I do believe it's better to remove support on `ethereum.nix`.  Thoughts @brianmcgee @selfuryon ?

**Comment by selfuryon** [comment]
Honestly, I've never heard about `plugeth` or used it. I agree that we can remove `plugeth`, but if someone is interested, we will restore it.

**Comment by brianmcgee** [comment]
Fine by me
