### ISSUE TITLE
How best to document everything?

### ISSUE THREAD

**Issue by brianmcgee** [nix-community/ethereum.nix#50]
The readme is only getting bigger. We should have a more robust set of docs. I'm open to suggestions.

**Comment by aldoborrero** [comment]
I think it's time to use either [mdbook](https://rust-lang.github.io/mdBook/) or [docsify](https://docsify.js.org/#/).

**Comment by aldoborrero** [comment]
We will stick with `mdbook` as it's quite simplistic to use.

**Comment by brianmcgee** [comment]
I'd like to throw [MkDocs](https://www.mkdocs.org/) into the mix, I see it around on a lot of nix projects.

**Comment by brianmcgee** [comment]
After speaking with the Numtide guys they are standardising on mkdocs. I had a look and it seems to be feature rich. An added bonus is I can just copy some of the setup and layout from projects like [Treefmt](https://github.com/numtide/treefmt) which I've already done in #147
