### ISSUE TITLE
Allow specifying btrfs sub volumes in geth service

### ISSUE THREAD

**Issue by brianmcgee** [nix-community/ethereum.nix#72]
This will be a more general feature eventually, but to begin with let's focus on the geth service and btrfs in particular.

The basic idea is to allow a user to specify that the `datadir` should be a btrfs subvolume. 

Before starting the geth client, the volume should be created if it hasn't already, with default mount options of `["discard" "noatime" "nodatacow"]`. If it already exists then ideally we validate the mount options match but that's not necessary for a first version.

I think we can leverage https://github.com/nix-community/disko. 

@Mic92 @Lassulus any advice/recommended approaches for integrating the service in `modules/geth.nix` with disko to achieve the outcome above?

**Comment by Lassulus** [comment]
hmm, right now disko only creates the whole disk configuration. incremental partition creation is not yet part of it (but I had a plan for it in the back of my head). I guess for the time being it would be easier to check the existence in some kind of ExecStartPre or a dependency unit and just create it, if it doesn't exist?
