### ISSUE TITLE
Add support for custom systemd targets

### ISSUE THREAD

**Issue by aldoborrero** [nix-community/ethereum.nix#76]
Whenever we want to run an Ethereum network, we usually need to execute a pair of EC (Execution Client) + Consensus client (CC). 

systemd allows us to create custom targets like example below:

```systemd
# named like ethereum-sepolia.target
[Unit]
Description=Ethereum Sepolia Service

# This collection of apps should be started at boot time.
[Install]
WantedBy=multi-user.target
```

With this, we can group related service units and control those as a group rather than per service instance:

```systemd
# In a file name like etherem-sepolia@.service
[Unit]
Description=%I Instance of App Web Service
PartOf=ethereum-sepolia.target

[Service]
ExecStart=/Command
Restart=on-failure
StandardOutput=journal

# Service definition for i.e prysm 

# When systemctl enable is used, make this start when the App service starts
[Install]
WantedBy=ethereum-sepolia.target
```

With that, we can spin up the service like:

```systemd start ethereum-sepolia``` 

And `systemd` will start both services.

All of the above is [pseudo-code that I've extracted from this StackOverflow thread](https://unix.stackexchange.com/a/283770) and that I've modified freely as an example.

**Comment by aldoborrero** [comment]
@brianmcgee since you're now leading the effort of systemd for so many services, would you be so kind to see a potential way of creating these custom target units?

**Comment by brianmcgee** [comment]
Having had time to play around with running some services I'm not sure this is something we should formalise within our own Nix module. I think instead we should document clearly how our modules create systemd services and add documentation explaining how to group them into their own targets with systemd and nix.

**Comment by aldoborrero** [comment]
This then belongs to documentation. I'll revamp our current labeling system to better convey this.
